### ISSUE TITLE
Constantly Needs Restart in Unity Mod Manager 

### ISSUE THREAD

**Issue by PonkyVT** [alterasc/CombatRelief#5] opened 2023-05-20 16:42 UTC
Haven't been able to get this to work in Pathfinder Wotr for some time now. Every time the mod menu opens now it says the "!!!" meaning the mod needs a restart, but no matter what I do it just is needing it constantly. I've uninstalled the mod, reinstalled it etc. Worked perfectly fine before I retook Drezen in the story, and then stopped completely after that.

**Comment by PonkyVT** [comment] 2023-05-20 16:44
Also, all settings for the mod disappear as well of course, just adding that in

**Comment by xADDBx** [comment] 2023-05-20 18:10
Could you post the log files Player.log and FullGameLog.txt from %userprofile%\AppData\LocalLow\Owlcat Games ?

**Comment by alterasc** [comment] 2023-05-23 13:14
Yes, please provide game logs.

**Comment by alterasc** [comment] 2023-06-06 21:08
Closing since no logs/reproduction steps are provided, and it all works for me.

If it happens again, please reopen this or create new one with more information.

**Closed as not planned by alterasc** 2023-06-06 21:08 UTC
